AllCops:
  NewCops: enable
  SuggestExtensions: false

Layout/SpaceInLambdaLiteral:
  EnforcedStyle: require_space

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Metrics/BlockLength:
  Exclude:
    - "app/api.rb"

Style/Documentation:
  Enabled: false

Style/HashSyntax:
  EnforcedShorthandSyntax: either

Style/StringLiterals:
  EnforcedStyle: double_quotes
