:concurrency: <%= ENV.fetch("SIDEKIQ_CONCURRENCY", 10) %>
:schedule:
  enqueue_appsflyer_pull_report_jobs:
    every: <%= "#{ENV.fetch("PING_INTERVAL", 60)} seconds" %>
    class: MonitoredHosts::PingEnqueueJob
    description: "Enqueues jobs to ping all monitored hosts"
